apps/news/urls.py
from django.urls import path,re_path
from . import views

app_name = 'news'

urlpatterns = [
    path('news_list/', views.news_list, name='news_list'),
    path('publish_comment/', views.publish_comment, name='publish_comment'),
    path('<int:news_id>/', views.news_detail, name='news_detail'),
    # path('',)
]

oztec/urls.py
# from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings

from apps.news import views
from apps.adminte.views import templateview
# import xadmin


urlpatterns = [
    # path('xadmin/', xadmin.site.urls),
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    re_path('templates/(?P<template>.*)/$', templateview, name='template'),
    path('news/', include('apps.news.urls', namespace='news')),
    path('account/', include('apps.ozauth.urls', namespace='ozauth')),
    path('adminlte/', include('apps.adminte.urls', namespace='adminlte')),
    path('courses/', include('apps.courses.urls', namespace='courses')),
    path('payinfo/', include('apps.payinfo.urls', namespace='payinfo')),
    path('ueditor/', include('apps.ueditor.urls', namespace='ueditor')),
    # re_path(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path("__debug__/",include(debug_toolbar.urls)))

front/templates/common/auth.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="../../dist/css/common/auth.min.css">
    <link rel="stylesheet" href="//at.alicdn.com/t/font_695382_9mjt9mwz38d.css">
    <script src="../../dist/js/jquery-3.3.1.js"></script>
    <script src="../../dist/js/auth.min.js"></script>
</head>
<body>
    <button id="auth">signin</button>
    <div class="mask-wrapper">
        <div class="auth-wrapper">
            <div class="close-group">
                <span class="close-btn icon-close iconfont"></span>
            </div>
            <div class="auth-group">
                <div class="auth-inner-group">
                    <div class="signin-group auth-item">
                        <div class="top-group">
                            <span class="title">请登录</span>
                            <a href="javascript:void(0);" class="switch">立即注册></a>
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <input type="text" class="form-control" name="username" placeholder="请输入用户名">
                            </div>
                            <div class="input-group">
                                <input type="password" class="form-control" name="password" placeholder="请输入密码">
                            </div>
                            <div class="input-group">
                                <lable><input type="checkbox" name="remember-me" class="remember">&nbsp;&nbsp;记住我</lable>
                            </div>
                            <div class="input-group">
                                <input type="submit" value="立即登录" class="submit-btn">
                            </div>
                        </div>
                    </div>
                    <div class="signup-group auth-item">
                        <div class="top-group">
                            <span class="title">请注册</span>
                            <a href="javascript:void(0);" class="switch">立即登录></a>
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <input type="text" class="form-control" name="telephone" placeholder="手机号码">
                            </div>
                            <div class="input-group">
                                <input type="text" class="form-control" name="username" placeholder="用户名">
                            </div>
                            <div class="input-group">
                                <div class="short-input-group">
                                    <input type="text" class="form-control" name="img_captcha" placeholder="图形验证码">
                                </div>
                                <div class="input-group-addon">
                                    <img src="http://img5.imgtn.bdimg.com/it/u=1320441599,4127074888&fm=27&gp=0.jpg" alt="">
                                </div>
                            </div>
                            <div class="input-group">
                                <input type="text" class="form-control" name="username" placeholder="密码">
                            </div>
                            <div class="input-group">
                                <input type="text" class="form-control" name="username" placeholder="确认密码">
                            </div>
                            <div class="input-group">
                                <div class="short-input-group">
                                    <input type="text" class="form-control" name="sms-captcha" placeholder="短信验证码">
                                </div>
                                <div class="input-group-addon">
                                    <span class="sms-captcha-btn">发送短信</span>
                                </div>
                            </div>
                            <div class="input-group">
                                <input type="submit" value="立即登录" class="submit-btn">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

front/templates/common/slidebar.html
{% load news_filters %}
<div class="sidebar-wrapper">
    <div class="title-group">
        <span class="title">在线课堂</span>
        <a href="" class="more">更多</a>
    </div>
    <div class="advertise-group">
        <a href=""><img src="https://www.xfz.cn/static/build/images/side-gift-banner.png" alt=""></a>
    </div>
    <div class="platform-group">
        <div class="title-group">
            <span class="title">关注小饭桌</span>
        </div>
        <div class="focus-group">
            <ul class="left-group">
                <li class="zhihu"><a href="" target="_blank">小饭桌创业课堂</a></li>
                <li class="weibo"><a href="" target="_blank">小饭桌创业课堂</a></li>
                <li class="toutiao"><a href="" target="_blank">小饭桌</a></li>
            </ul>
            <div class="right-group">
                <p class="desc">扫码关注</p>
            </div>
        </div>
    </div>
    <div class="hot-news-group">
        <div class="title-group">
            <span class="title">热门推荐</span>
        </div>
        <ul class="hot-list-group">
            {% for hot_new in hot_news %}
                <li>
                    <div class="left-group">
                        <p class="title"><a href="{% url 'news:news_detail' hot_new.id %}">{{ hot_new.title }}</a></p>
                        <p class="more">
                            <span class="category">{{ hot_new.categoty.name }}</span>
                            <span class="pub-time">{{ hot_new.pub_time|time_since }}</span>
                        </p>
                    </div>
                    <div class="right-group">
                        <a href="{% url 'news:news_detail' hot_new.id %}"><img src="{{ hot_new.thumbnail }}" alt=""></a>
                    </div>
                </li>
            {% endfor %}



        </ul>
    </div>
</div>